Updtaed the faq.html file
Real-Dev-Squad/website-welcome pull request #103
Opened 2021-03-04 17:02 UTC by ASHWINIAJIT

- Added the Status site which uses Next.js, TypeScript
- Added Next.js in the Members site
- Commented out the entries for Main App and Events
- Added the My Site which uses Ember
- Added the Main Site which uses HTML, CSS, Javascript

2021-03-04 19:03 UTC, swarajpure requested changes
Good job there!

Congratulations on your first PR in Real Dev Squad! 🎉 

Suggesting some minor changes

2021-03-04 19:03 UTC, swarajpure commented on faq.html
> +                <li><a href="https://github.com/Real-Dev-Squad/website-members" target="_blank" rel="noopener noreferrer">Members</a> : React, Next.js</li>
Can we just have `Next.js` for members?

2021-03-04 19:03 UTC, swarajpure commented on faq.html
> +                <!-- <li><a href="https://github.com/Real-Dev-Squad/rds-events-website" target="_blank" rel="noopener noreferrer">Events</a>: React</li> -->
We won't be sending comments in production. Can we please not have them?

2021-03-04 19:03 UTC, swarajpure commented on faq.html
> +                <li><a href="https://github.com/Real-Dev-Squad/website-backend" target="_blank" rel="noopener noreferrer">Backend</a> : Node.js</li>
I like how you have maintained the order of the projects... From simple HTML, CSS to frontend frameworks and then backend 😁

2021-03-05 17:22 UTC, swarajpure approved these changes
Great. Thank you! 🎉

2021-03-05 18:33 UTC, Rucha1499 approved these changes
Good job! Thank you 🎉

2021-03-05 18:34 UTC, merged