fix for faq page css on develop branch
Real-Dev-Squad/website-welcome pull request #191
Opened 2021-11-07 17:56 UTC by ican8

2021-11-08 12:49 UTC, Rucha1499 reviewed
Thanks for this pull request! @ican8
Can you please add the screenshots of the faq page (updated), so that it becomes easy for reviewing? Add one for desktop and one for mobile.

2021-11-08 18:22 UTC, swarajpure commented on css/common/main.css
> +    max-width: 1140px;
What is I have an ultra wide monitor? This container will take 1140px of it and rest of it will be just blank?

2021-11-08 18:25 UTC, swarajpure requested changes

2021-11-08 18:25 UTC, swarajpure commented on css/common/main.css
> +  font-size: 20px;
Please read this answer to know about using px or rem for font-size: https://stackoverflow.com/a/11803273

2021-11-09 05:05 UTC, ican8 commented
Updated FAQ page

![desktop](https://user-images.githubusercontent.com/56404461/140865656-6f73e0ca-341e-4d54-871d-4b7352d9ef67.PNG)

![mobile](https://user-images.githubusercontent.com/56404461/140865672-6c4de390-37af-4540-9454-b6f0cd90af54.png)

2021-12-01 17:48 UTC, swarajpure approved these changes
Looks good to me!

2021-12-02 06:21 UTC, merged