add meta tags
Real-Dev-Squad/website-welcome pull request #223
Opened 2022-01-20 08:32 UTC by 7ORP3DO

Add basic meta tags.

linked Issue: #219

2022-01-29 18:09 UTC, Rucha1499 reviewed
Thank you @7ORP3DO for the PR! Good job here. 🔥 

Adding some comments, please have a look at them

2022-01-29 18:09 UTC, Rucha1499 commented on index.html
> +    <meta name="keywords" content="RDS, developers,Real Dev Squad" />
I came across some blogs/ docs which state that the meta tag `keywords` is not currently used as it is not considered for page ranking and has no SEO value as such. For reference -> https://developers.google.com/search/blog/2009/09/google-does-not-use-keywords-meta-tag

should will still consider adding it? what are your thoughts on it?

2022-02-05 16:52 UTC, ankushdharkar requested changes
@7ORP3DO Could you address the comments and resolve them please

2022-02-11 06:09 UTC, Rucha1499 commented
Closing this PR due to inactivity.

2022-02-11 06:09 UTC, closed without merging