Codeofconduct
Real-Dev-Squad/website-welcome pull request #73
Opened 2020-10-26 16:53 UTC by ashishmangla0

![image](https://user-images.githubusercontent.com/24789070/97202634-df804680-17d9-11eb-8a5c-3c9df3659be9.png)

2020-10-31 03:41 UTC, strider99 reviewed
css looks good

2020-10-31 03:41 UTC, strider99 commented on css/pages/coc.css
> +@keyframes moveLeftBounce {
@ashishmangla0  do we need the animation

2020-10-31 10:15 UTC, ashishmangla0 commented
Thanks

2020-11-02 19:34 UTC, ankushdharkar commented on discord.html
> +            <span></span>
Why 3 empty spans?

2020-11-03 05:21 UTC, ankushdharkar requested changes

2020-11-03 05:21 UTC, ankushdharkar commented on code-of-conduct.html
> +									Share a <a href="https://codepen.io/" target="_blank" rel="nopener norefer">Codepen </a>link
Type. Correct: `noopener noreferrer`

2020-11-03 05:21 UTC, ankushdharkar commented on code-of-conduct.html
> +				href="https://github.com/Real-Dev-Squad/website-welcome" target="_blank" rel="nopener norefer"> open
Please fix: `noopener noreferrer`

2020-11-03 05:21 UTC, ankushdharkar commented on code-of-conduct.html
> +									instead of a <a href="https://github.com/" target="_blank" rel="nopener norefer">Github
Please fix: `noopener noreferrer`

2020-11-03 05:21 UTC, ankushdharkar commented on discord.html
> +            <span></span>
Why empty spans?

2020-11-03 05:41 UTC, ashishmangla0 commented on discord.html
> +            <span></span>
Span tags are bars for responsive.

2020-11-03 05:42 UTC, ashishmangla0 commented on code-of-conduct.html
> +				href="https://github.com/Real-Dev-Squad/website-welcome" target="_blank" rel="nopener norefer"> open
I will also fix these

2020-11-03 05:43 UTC, ankushdharkar commented on discord.html
> +            <span></span>
Please use classes to denote this

2020-11-06 02:58 UTC, ashishmangla0 commented on code-of-conduct.html
> +				href="https://github.com/Real-Dev-Squad/website-welcome" target="_blank" rel="nopener norefer"> open
fixed noopener noreferrer

2020-11-06 03:01 UTC, ashishmangla0 commented on discord.html
> +            <span></span>
fixed

2020-11-08 12:36 UTC, ashishmangla0 commented on discord.html
> +            <span></span>
its fixed

2020-11-08 12:38 UTC, ashishmangla0 commented on code-of-conduct.html
> +									Share a <a href="https://codepen.io/" target="_blank" rel="nopener norefer">Codepen </a>link
fixed that

2020-11-23 15:12 UTC, ashishmangla0 commented on code-of-conduct.html
> +									instead of a <a href="https://github.com/" target="_blank" rel="nopener norefer">Github
fixed

2020-12-05 10:13 UTC, closed without merging