Fix FAQ icons
Real-Dev-Squad/website-welcome pull request #98
Opened 2021-02-27 12:40 UTC by ashwindevx

2021-02-27 17:34 UTC, Rucha1499 reviewed
Congratulations on your first PR in RDS! 🎉 

Can you add a short video/ gif to the description of the PR?  It will be easy to visualize.

2021-02-28 07:25 UTC, ashwindevx commented
@Rucha1499 I made these icons change when clicking.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/59074550/109410866-194d9d80-79c4-11eb-978c-18961e040a05.gif)

2021-02-28 07:33 UTC, tejasberi commented on js/faq.js
> +  eachBtn.addEventListener('click', function(e) {
do we need a removeEventListener at some point?

2021-03-04 10:01 UTC, swarajpure requested changes
Can you please revert the changes in the files which are not supposed to be a part of this PR?

I can see that the commit `Merge branch 'develop' into develop` is removing a couple of files which are required for this project.

As of now, you can either revert that particular commit or you could directly copy paste the whole file which is not related to your task, that way there will be less number of files changed since the develop branch and your branch will be having the same version of files which are not related to your task.

Thank you! 🎉

2021-03-04 10:54 UTC, ashwindevx commented
![image](https://user-images.githubusercontent.com/59074550/109953414-09a4c080-7d06-11eb-9880-2a2bf6a43d24.png)
I'm getting this error. I don't know how to fix it.

2021-03-05 10:22 UTC, swarajpure commented
> 
> 
> ![image](https://user-images.githubusercontent.com/59074550/109953414-09a4c080-7d06-11eb-9880-2a2bf6a43d24.png)
> I'm getting this error. I don't know how to fix it.

I don't know what app you're using.
You could try the other solution which I have suggested in the review 👍🏻 

> you could directly copy paste the whole file which is not related to your task, that way there will be less number of files changed since the develop branch and your branch will be having the same version of files which are not related to your task.

Commit and push that, let's see if that works.

2021-03-07 06:46 UTC, swarajpure commented
Closing as the author did not respond in 2 days

2021-03-07 06:46 UTC, closed without merging